### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by trmid** [WeaverFi/weaverfi#10]
**Bug Description:**
As described here:
https://github.com/WeaverFi/weaverfi/commit/c28312d6d4a1bdd840f0a231f46f18ed3a9969c8#commitcomment-89006513

**Reproduction Steps:**
1. Query your **empty** balance of a token with the weaverfi RPCs
2. Acquire a balance of a said token
3. Query your balance of that token with the weaverfi RPCs

**Expected Behavior:**
All responses should return your token balance within a reasonable time frame (a few minutes at most). (Ankr seems to have longer response cache times than other RPCs which can cause issues on front-ends using weaverfi to query user balances as a part of feature-gating)

**Comment by Ncookiez** [comment]
I've gone ahead and changed the order of the RPCs being used on Optimism on c96074a

The cache time on Ankr public RPCs really does seem to be an issue - reluctantly I've left them as last option on most chains in case all others fail.

In any case, for dapps specifically using an RPC for feature-gating right after a transaction for example, I imagine most will use the RPC and provider from the connected wallet instead of a public one from the SDK (as I should be doing in all cases, whoops...).

I do think the ability to use custom RPCs throughout the SDK would be a valuable addition, however.
